const CATEGORIES=[['all','All Services','✦'],['hair','Hair','✂️'],['nails','Nails','💅'],['lashes','Lashes','👁️'],['brows','Brows','✨'],['skin','Facials','🧖‍♀️'],['makeup','Makeup','💄'],['wax','Waxing','🌸']];
const SERVICES=[
{id:'s1',cat:'hair',name:'Signature Cut & Blowout',desc:'Consultation, precision cut, wash and polished blow-dry finish.',price:95,duration:75,emoji:'✂️',featured:true,addons:[['Deep Conditioning',25],['Scalp Treatment',30]]},
{id:'s2',cat:'hair',name:'Glossy Hair Color',desc:'Rich all-over color with professional finish and shine treatment.',price:180,duration:120,emoji:'🎨',featured:true,addons:[['Toner',35],['Bond Repair',45]]},
{id:'s3',cat:'hair',name:'Balayage & Style',desc:'Hand-painted dimensional highlights customized to your features.',price:320,duration:210,emoji:'✨',featured:true,addons:[['Bond Repair',45],['Haircut',55]]},
{id:'s4',cat:'nails',name:'Luxury Gel Manicure',desc:'Nail shaping, cuticle care, gel color and nourishing hand finish.',price:75,duration:60,emoji:'💅',featured:true,addons:[['French Tips',15],['Nail Art',20]]},
{id:'s5',cat:'nails',name:'Spa Pedicure',desc:'Relaxing soak, detailed nail care, exfoliation, massage and color.',price:85,duration:70,emoji:'🫧',featured:false,addons:[['Gel Upgrade',20],['Callus Care',15]]},
{id:'s6',cat:'lashes',name:'Classic Lash Extensions',desc:'Natural-looking individual lash extensions customized to your eyes.',price:150,duration:120,emoji:'👁️',featured:true,addons:[['Lash Bath',10],['Wispy Mapping',20]]},
{id:'s7',cat:'lashes',name:'Lash Lift & Tint',desc:'Lift, curl and deepen your natural lashes for an effortless look.',price:110,duration:75,emoji:'🌙',featured:false,addons:[['Keratin Treatment',20]]},
{id:'s8',cat:'brows',name:'Brow Sculpt & Tint',desc:'Mapping, shaping and custom tint for balanced, defined brows.',price:65,duration:45,emoji:'✨',featured:true,addons:[['Brow Lamination',45]]},
{id:'s9',cat:'skin',name:'Signature Glow Facial',desc:'Deep cleanse, gentle exfoliation, hydration and luminous finishing mask.',price:140,duration:75,emoji:'🧖‍♀️',featured:true,addons:[['LED Therapy',35],['Eye Treatment',20]]},
{id:'s10',cat:'skin',name:'Hydra Renewal Facial',desc:'Intensive hydration and barrier-support treatment for soft radiant skin.',price:190,duration:90,emoji:'💧',featured:false,addons:[['LED Therapy',35],['Neck Treatment',30]]},
{id:'s11',cat:'makeup',name:'Event Glam Makeup',desc:'Long-wear professional makeup tailored to your event and style.',price:160,duration:75,emoji:'💄',featured:true,addons:[['Strip Lashes',25],['Hair Styling',80]]},
{id:'s12',cat:'wax',name:'Full Face Waxing',desc:'Gentle facial hair removal with soothing post-wax skincare.',price:70,duration:40,emoji:'🌸',featured:false,addons:[['Brow Shaping',20]]}
];
const STAFF=[{id:'st1',name:'Maya Laurent',role:'Senior Hair Stylist',skills:['hair'],initials:'ML',rating:4.9},{id:'st2',name:'Sofia Kim',role:'Nail Artist',skills:['nails'],initials:'SK',rating:4.9},{id:'st3',name:'Amira Noor',role:'Lash & Brow Artist',skills:['lashes','brows'],initials:'AN',rating:5.0},{id:'st4',name:'Chloe Martin',role:'Skin Therapist',skills:['skin','wax'],initials:'CM',rating:4.8},{id:'st5',name:'Lina Rose',role:'Makeup Artist',skills:['makeup'],initials:'LR',rating:4.9},{id:'st6',name:'Emma Jade',role:'Beauty Specialist',skills:['hair','makeup'],initials:'EJ',rating:4.8}];
const TIMES=['9:00 AM','10:00 AM','11:30 AM','1:00 PM','2:30 PM','4:00 PM','5:30 PM','7:00 PM'];
let state={category:'all',search:'',bookingStep:1,service:null,stylist:null,date:'',time:'',addons:[],adminTab:'appointments'};
const $=id=>document.getElementById(id); const money=n=>`RM${Number(n).toFixed(0)}`;
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getBookings(){return JSON.parse(localStorage.getItem('lumea_bookings')||'[]')} function saveBookings(v){localStorage.setItem('lumea_bookings',JSON.stringify(v))}
function showToast(msg,type=''){const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;$('toast-wrap').appendChild(t);setTimeout(()=>t.remove(),3200)}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='bookings-view')renderBookingStatus();if(id==='admin-view')renderAdmin()}
document.addEventListener('DOMContentLoaded',()=>{renderCategories();renderServices();renderSpecialists();wire();updateBookingDot();const d=new Date();d.setDate(d.getDate()+1);$('booking-date').min=d.toISOString().split('T')[0]});
function wire(){document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('brand-home').onclick=()=>switchView('services-view');$('header-book-btn').onclick=$('hero-book-btn').onclick=()=>openBooking(SERVICES[0]);$('explore-btn').onclick=()=>$('services-section').scrollIntoView({behavior:'smooth'});$('search-input').oninput=e=>{state.search=e.target.value.toLowerCase();renderServices()};$('close-booking').onclick=closeBooking;$('booking-next').onclick=nextBooking;$('booking-back').onclick=backBooking;$('booking-date').onchange=e=>{state.date=e.target.value;state.time='';renderTimes()};$('login-form').onsubmit=e=>{e.preventDefault();if($('login-email').value==='admin@lumea.com'&&$('login-password').value==='admin123'){localStorage.setItem('lumea_admin','1');showToast('Welcome to the salon dashboard','success');renderAdmin()}else showToast('Invalid demo credentials','danger')};$('logout-btn').onclick=()=>{localStorage.removeItem('lumea_admin');renderAdmin()};document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.adminTab=b.dataset.tab;renderAdminPane()})}
function renderCategories(){$('category-pills').innerHTML=CATEGORIES.map(([id,n,e])=>`<button class="pill ${state.category===id?'active':''}" data-cat="${id}">${e} ${n}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderCategories();renderServices()})}
function renderServices(){let list=SERVICES.filter(s=>(state.category==='all'||s.cat===state.category)&&(!state.search||(s.name+' '+s.desc).toLowerCase().includes(state.search)));$('service-count').textContent=`${list.length} services`;$('empty-services').classList.toggle('hidden',list.length>0);$('services-grid').innerHTML=list.map(s=>`<article class="service-card"><div class="service-art">${s.featured?'<span class="featured">CLIENT FAVORITE</span>':''}<span>${s.emoji}</span></div><div class="service-body"><h3>${esc(s.name)}</h3><p>${esc(s.desc)}</p><div class="meta"><span><i class="fa-regular fa-clock"></i> ${s.duration} min</span><span>★ 4.9</span></div><div class="service-foot"><span class="price">${money(s.price)}</span><button class="btn btn-primary book-service" data-id="${s.id}">Book</button></div></div></article>`).join('');document.querySelectorAll('.book-service').forEach(b=>b.onclick=()=>openBooking(SERVICES.find(s=>s.id===b.dataset.id)))}
function renderSpecialists(){$('specialists-grid').innerHTML=STAFF.slice(0,4).map(s=>`<div class="specialist-card"><div class="avatar">${s.initials}</div><h3>${s.name}</h3><p>${s.role}</p><p>★ ${s.rating}</p></div>`).join('')}
function openBooking(service){state.service=service;state.bookingStep=1;state.stylist=null;state.date='';state.time='';state.addons=[];$('modal-service-name').textContent=service.name;$('modal-service-meta').textContent=`${service.duration} min · from ${money(service.price)}`;$('selected-service-card').innerHTML=`<div class="selected-service"><div><b>${esc(service.name)}</b><small style="display:block;color:var(--muted)">${service.duration} minutes</small></div><b>${money(service.price)}</b></div>`;$('addon-list').innerHTML=service.addons.length?service.addons.map((a,i)=>`<button class="option" data-addon="${i}">${esc(a[0])} +${money(a[1])}</button>`).join(''):'<span class="muted">No add-ons for this service.</span>';document.querySelectorAll('[data-addon]').forEach(b=>b.onclick=()=>{const a=service.addons[+b.dataset.addon];b.classList.toggle('selected');if(b.classList.contains('selected'))state.addons.push(a);else state.addons=state.addons.filter(x=>x[0]!==a[0]);updateTotal()});renderStylists();renderTimes();setBookingStep(1);updateTotal();$('booking-modal').classList.remove('hidden')}
function closeBooking(){$('booking-modal').classList.add('hidden')}
function renderStylists(){const eligible=STAFF.filter(s=>s.skills.includes(state.service.cat));$('stylist-options').innerHTML=eligible.map(s=>`<button class="stylist-option ${state.stylist?.id===s.id?'selected':''}" data-stylist="${s.id}"><span class="avatar">${s.initials}</span><span style="text-align:left"><b>${s.name}</b><small style="display:block;color:var(--muted)">${s.role} · ★ ${s.rating}</small></span></button>`).join('');document.querySelectorAll('[data-stylist]').forEach(b=>b.onclick=()=>{state.stylist=STAFF.find(s=>s.id===b.dataset.stylist);renderStylists()})}
function renderTimes(){$('time-options').innerHTML=TIMES.map(t=>`<button class="time-option ${state.time===t?'selected':''}" data-time="${t}">${t}</button>`).join('');document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{state.time=b.dataset.time;renderTimes()})}
function updateTotal(){const total=state.service.price+state.addons.reduce((a,x)=>a+x[1],0);$('booking-total').textContent=money(total)}
function setBookingStep(n){state.bookingStep=n;document.querySelectorAll('.step-pane').forEach((p,i)=>p.classList.toggle('active',i===n-1));document.querySelectorAll('.booking-steps .step').forEach((s,i)=>s.classList.toggle('active',i===n-1));$('booking-back').classList.toggle('hidden',n===1);$('booking-next').textContent=n===4?'Confirm Booking':'Continue'}
function nextBooking(){if(state.bookingStep===2&&!state.stylist)return showToast('Please choose a specialist','danger');if(state.bookingStep===3&&(!state.date||!state.time))return showToast('Please choose a date and time','danger');if(state.bookingStep<4)return setBookingStep(state.bookingStep+1);const name=$('client-name').value.trim(),phone=$('client-phone').value.trim(),email=$('client-email').value.trim();if(!name||!phone||!email)return showToast('Please complete your name, phone and email','danger');const total=state.service.price+state.addons.reduce((a,x)=>a+x[1],0);const booking={id:`LM-${Math.floor(1000+Math.random()*9000)}`,serviceId:state.service.id,serviceName:state.service.name,stylistId:state.stylist.id,stylistName:state.stylist.name,date:state.date,time:state.time,clientName:name,phone,email,notes:$('client-notes').value.trim(),addons:state.addons,total,status:'confirmed',createdAt:new Date().toISOString()};const list=getBookings();list.unshift(booking);saveBookings(list);localStorage.setItem('lumea_active_booking',booking.id);closeBooking();updateBookingDot();showToast(`Appointment ${booking.id} confirmed!`,'success');switchView('bookings-view')}
function backBooking(){if(state.bookingStep>1)setBookingStep(state.bookingStep-1)}
function updateBookingDot(){$('booking-dot').classList.toggle('hidden',!localStorage.getItem('lumea_active_booking'))}
function renderBookingStatus(){const id=localStorage.getItem('lumea_active_booking'),b=getBookings().find(x=>x.id===id);if(!b){$('booking-status-card').innerHTML=`<div class="empty"><i class="fa-regular fa-calendar"></i><h3>No appointment yet</h3><p>Choose a service and book your beauty moment.</p><button class="btn btn-primary" id="empty-book">Browse Services</button></div>`;$('empty-book').onclick=()=>switchView('services-view');return}const stages=['confirmed','checked-in','in-progress','completed'],idx=Math.max(0,stages.indexOf(b.status));$('booking-status-card').innerHTML=`<div style="display:flex;justify-content:space-between;gap:15px;align-items:start"><div><span class="eyebrow">BOOKING ${b.id}</span><h2 style="font-family:var(--serif);margin:5px 0">${esc(b.serviceName)}</h2><span class="status">${b.status.toUpperCase()}</span></div><b class="price">${money(b.total)}</b></div><div class="timeline">${stages.map((s,i)=>`<div class="timeline-step ${i<idx?'done':''} ${i===idx?'active':''}"><i class="fa-solid ${['fa-calendar-check','fa-door-open','fa-wand-magic-sparkles','fa-check'][i]}"></i>${['Confirmed','Checked In','In Service','Completed'][i]}</div>`).join('')}</div><div class="detail-grid"><div class="detail"><small>Date & time</small><b>${b.date} · ${b.time}</b></div><div class="detail"><small>Specialist</small><b>${esc(b.stylistName)}</b></div><div class="detail"><small>Client</small><b>${esc(b.clientName)}</b></div><div class="detail"><small>Add-ons</small><b>${b.addons.length?b.addons.map(a=>esc(a[0])).join(', '):'None'}</b></div></div>`}
function renderAdmin(){const auth=localStorage.getItem('lumea_admin')==='1';$('admin-login').classList.toggle('hidden',auth);$('admin-dashboard').classList.toggle('hidden',!auth);if(auth){updateKPIs();renderAdminPane()}}
function updateKPIs(){const b=getBookings();$('kpi-appointments').textContent=b.length;$('kpi-revenue').textContent=money(b.filter(x=>x.status!=='cancelled').reduce((a,x)=>a+x.total,0));$('kpi-upcoming').textContent=b.filter(x=>['confirmed','checked-in','in-progress'].includes(x.status)).length;$('kpi-completed').textContent=b.filter(x=>x.status==='completed').length}
function renderAdminPane(){if(state.adminTab==='appointments')renderAdminAppointments();else if(state.adminTab==='services')renderAdminServices();else renderAdminStaff()}
function renderAdminAppointments(){const list=getBookings();$('admin-pane').innerHTML=`<div class="admin-list">${list.length?list.map(b=>`<div class="admin-row card"><div><b>${b.id} · ${esc(b.clientName)}</b><small style="display:block">${esc(b.serviceName)} with ${esc(b.stylistName)} · ${b.date} ${b.time}</small></div><div class="row-actions">${['confirmed','checked-in','in-progress','completed'].map(s=>`<button class="mini-btn ${b.status===s?'active':''}" data-status="${s}" data-booking="${b.id}">${s}</button>`).join('')}</div></div>`).join(''):'<div class="empty card">No appointments yet.</div>'}</div>`;document.querySelectorAll('[data-booking]').forEach(btn=>btn.onclick=()=>{const all=getBookings(),i=all.findIndex(x=>x.id===btn.dataset.booking);all[i].status=btn.dataset.status;saveBookings(all);updateKPIs();renderAdminAppointments();if(localStorage.getItem('lumea_active_booking')===all[i].id)renderBookingStatus();showToast('Appointment status updated','success')})}
function renderAdminServices(){$('admin-pane').innerHTML=`<div class="admin-list">${SERVICES.map(s=>`<div class="admin-row card"><div><b>${s.emoji} ${esc(s.name)}</b><small style="display:block">${CATEGORIES.find(c=>c[0]===s.cat)?.[1]} · ${s.duration} min</small></div><div><b>${money(s.price)}</b> <span class="status">${s.featured?'Featured':'Active'}</span></div></div>`).join('')}</div>`}
function renderAdminStaff(){$('admin-pane').innerHTML=`<div class="specialists-grid">${STAFF.map(s=>`<div class="specialist-card"><div class="avatar">${s.initials}</div><h3>${s.name}</h3><p>${s.role}</p><p>★ ${s.rating}</p><span class="status">Available</span></div>`).join('')}</div>`}
